easy_admin:
    site_name: 'Aqua<i>Note</i>'
    entities:
       # List the entity class name you want to manage
      User:
        class: App\Entity\User
        list:
          sort: ['id', 'ASC']
      Role:
        class: App\Entity\Role
      UserRole:
        class: App\Entity\UserRole
      FileImport:
        class: App\Entity\FileImport
        controller: App\Controller\EasyAdmin\FileImportController
        label: Import
        help: Genuses are not covered under warranty!
        form:
          fields:  
            - {property: 'file_name', type: 'file'}